version: "3.9"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'restaurantedb'
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: mysql
    networks:
      - microservices-bridge

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq-service
    hostname: rabbitmq-service
    networks:
      - microservices-bridge
    depends_on:
      - mysql

  itemservice:
    image: itemservice:3.0
    restart: always
    container_name: item-service
    networks:
      - microservices-bridge
    ports:
      - 12126:80
    depends_on:
      - rabbitmq

  restauranteservice:
    image: restauranteservice:2.5
    restart: always
    container_name: restaurante-service
    networks:
      - microservices-bridge
    ports:
      - 12127:80
    depends_on:
      - itemservice
    

networks:
  microservices-bridge:
    driver: bridge
