DECLARE @PRODUTO_ALEATORIO VARCHAR(12)
DECLARE @VAL_INICIAL INT
DECLARE @VAL_FINAL INT
DECLARE @ALEATORIO INT
DECLARE @CONTADOR INT
SET @CONTADOR = 1
SET @VAL_INICIAL = 1
SELECT @VAL_FINAL = COUNT(*) FROM [TABELA DE PRODUTOS]
SET @ALEATORIO = [dbo].[NumeroAleatorio](@VAL_INICIAL, @VAL_FINAL)
DECLARE CURSOR1 CURSOR FOR SELECT [CODIGO DO PRODUTO] 
    FROM [TABELA DE PRODUTOS]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @PRODUTO_ALEATORIO
WHILE @CONTADOR <= @ALEATORIO
BEGIN
    FETCH NEXT FROM CURSOR1 INTO @PRODUTO_ALEATORIO
    SET @CONTADOR = @CONTADOR + 1
END
CLOSE CURSOR1
DEALLOCATE CURSOR1
SELECT @PRODUTO_ALEATORIO