
IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL DROP TABLE TABELA_TESTE;
IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL CREATE TABLE TABELA_TESTE (ID VARCHAR(10));

SELECT  GETDATE() 
SELECT DATENAME(WEEKDAY, DATEADD(DAY, 6, GETDATE()))

DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT

SET @NUMERO_DIAS = 10
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()));

PRINT @DIA_SEMANA;
IF @DIA_SEMANA = 'Domingo' OR @DIA_SEMANA = 'Sábado'
	PRINT 'Este dia é fim de semana';
ELSE
	PRINT 'Este dia é dia da semana';


DECLARE @DATA_NOTA DATE;
DECLARE @QUANT_NOTA INT;

SET @DATA_NOTA = '2015-01-01';

SELECT @QUANT_NOTA = COUNT(*) 
FROM [NOTAS FISCAIS]
WHERE DATA = @DATA_NOTA;

PRINT @QUANT_NOTA
IF @QUANT_NOTA > 70
	PRINT 'Muita nota';
ELSE
	PRINT 'Pouca nota';


SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
WHERE BAIRRO = 'Jardins'


DECLARE @LIMITE_MAXIMO FLOAT, @LIMITE_ATUAL FLOAT
DECLARE @BAIRRO VARCHAR(20)

SET @BAIRRO = 'Água Santa'
SET @LIMITE_MAXIMO = 40000

SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO]) 
FROM [TABELA DE CLIENTES] 
WHERE BAIRRO = @BAIRRO;

IF @LIMITE_MAXIMO <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO)
BEGIN
	PRINT 'Valor estourou. Não é possível abrir novos creditos';
END
ELSE
BEGIN
	PRINT 'Valor não estourou. É possível abrir novos creditos';
END	


DECLARE @DATA_NOTA2 DATE;

SET @DATA_NOTA2 = '2015-01-01';

IF (SELECT COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATA_NOTA2) > 70
BEGIN
	PRINT 'Muita nota';
END
ELSE
BEGIN
	PRINT 'Pouca nota';
END