CREATE PROCEDURE BuscaPorEntidades @ENTIDADE AS VARCHAR(10)
AS
BEGIN
	IF @ENTIDADE = 'CLIENTES'
		SELECT CPF AS IDENTIFICADOR, NOME AS DESCRITOR, BAIRRO FROM [TABELA DE CLIENTES]
	ELSE IF @ENTIDADE = 'VENDEDORES'
		SELECT MATRICULA AS IDENTIFICADOR, NOME AS DESCRITOR, BAIRRO FROM [TABELA DE VENDEDORES]
END

EXEC BuscaPorEntidades @ENTIDADE = 'CLIENTES';

EXEC BuscaPorEntidades @ENTIDADE = 'VENDEDORES';



CREATE PROCEDURE BuscaPorEntidadesCompleta @ENTIDADE AS VARCHAR(10)
AS
BEGIN
	IF @ENTIDADE = 'CLIENTES'
		SELECT CPF AS IDENTIFICADOR, NOME AS DESCRITOR, BAIRRO FROM [TABELA DE CLIENTES]
	ELSE IF @ENTIDADE = 'VENDEDORES'
		SELECT MATRICULA AS IDENTIFICADOR, NOME AS DESCRITOR, BAIRRO FROM [TABELA DE VENDEDORES]
	ELSE IF @ENTIDADE = 'PRODUTOS'
		SELECT [CODIGO DO PRODUTO] AS CODIGO, [NOME DO PRODUTO] AS PRODUTO FROM [TABELA DE PRODUTOS]
END

EXEC BuscaPorEntidadesCompleta @ENTIDADE = 'PRODUTOS'