CREATE TABLE [CLIENTES]
([CPF][NVARCHAR](11),
 [NOME][NVARCHAR](100),
 [ENDERECO1][NVARCHAR](150),
 [ENDERECO2][NVARCHAR](150),
 [BAIRRO][NVARCHAR](50),
 [CIDADE][NVARCHAR](50),
 [ESTADO][NVARCHAR](2),
 [CEP][NVARCHAR](8),
 [DATA_NASCIMENTO][DATE],
 [IDADE][SMALLINT],
 [SEXO][NVARCHAR](1),
 [LIMITE_CREDITO][MONEY],
 [VOLUME_COMPRA][FLOAT],
 [PRIMEIRA_COMPRA][BIT]);

 CREATE TABLE [VENDEDORES]
 ([MATRICULA][NVARCHAR](5),
  [NOME][NVARCHAR](100),
  [PERCENTUAL_COMISSAO][FLOAT]
 );