CREATE DATABASE SUCOS_VENDA_01;

CREATE DATABASE SUCOS_VENDA_02
ON (NAME=SUCOS_VENDA_DAT, 
	FILENAME = 'C:\TEMP\DATA\SALES_VENDA_02.MDF',
	SIZE = 10,
	MAXSIZE = 50, 
	FILEGROWTH = 5)
LOG ON (NAME=SUCO_VENDAS_LOG,
		FILENAME = 'C:\TEMP\DATA\SALES_VENDA_02.LDF',
		SIZE = 10,
		MAXSIZE = 50, 
		FILEGROWTH = 5);