DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR (100);

SET @MATRICULA = '00240';
SET @NOME = 'Claudia Rodriges';
SET @PERCENTUAL = 0.10;
SET @DATA = '2012-03-12';
SET @FERIAS = 1;
SET @BAIRRO = 'Jardins'

INSERT INTO [TABELA DE VENDEDORES] 
(MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES
(@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO);

SELECT * FROM [TABELA DE VENDEDORES]

DECLARE @Cliente VARCHAR(10)
DECLARE @Idade INT
DECLARE @DataNascimento DATE
DECLARE @Custo FLOAT
SET @Cliente = 'João'
SET @Idade = 10
SET @DataNascimento = '20170110'
SET @Custo = 10.23
PRINT @Cliente
PRINT @Idade
PRINT @DataNascimento
PRINT @Custo

DECLARE @NUMNOTAS INT;
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = '20170101';
PRINT @NUMNOTAS;