SELECT A.CPF, A.NOME, SUM(C.QUANTIDADE * C.PREÇO) AS FATURAMENTO
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B ON A.CPF = B.CPF 
AND YEAR(B.DATA) = 2016
INNER JOIN [ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
GROUP BY A.CPF, A.NOME;

DROP TYPE ListaClientes;

CREATE TYPE ListaClientes AS TABLE
(CPF VARCHAR(12) NOT NULL);

DECLARE @Lista AS ListaClientes;
INSERT INTO @Lista (CPF) VALUES ('8502682733'), ('8719655770'), ('9283760794') ;
SELECT * FROM @Lista;

SELECT * FROM [TABELA DE CLIENTES];

DECLARE @Lista AS ListaClientes;
INSERT INTO @Lista (CPF) VALUES ('8502682733'), ('8719655770'), ('9283760794');

SELECT A.CPF, A.NOME, SUM(C.QUANTIDADE * C.PREÇO) AS FATURAMENTO
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B ON A.CPF = B.CPF 
AND YEAR(B.DATA) = 2016
INNER JOIN [ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
INNER JOIN @Lista D ON A.CPF = D.CPF
GROUP BY A.CPF, A.NOME;

CREATE PROCEDURE FaturamentoCliente2016
@LISTA AS ListaClientes READONLY 
AS
SELECT A.CPF, A.NOME, SUM(C.QUANTIDADE * C.PREÇO) AS FATURAMENTO
FROM [TABELA DE CLIENTES] A INNER JOIN [NOTAS FISCAIS] B ON A.CPF = B.CPF 
AND YEAR(B.DATA) = 2016
INNER JOIN [ITENS NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
INNER JOIN @LISTA D ON A.CPF = D.CPF
GROUP BY A.CPF, A.NOME;

DECLARE @Lista AS ListaClientes;
INSERT INTO @Lista (CPF) VALUES ('8502682733'), ('8719655770'), ('9283760794');

EXEC FaturamentoCliente2016 @LISTA = @Lista;

SELECT * FROM [TABELA DE CLIENTES];



SELECT * FROM [NOTAS FISCAIS]

CREATE TYPE ListarDatas AS TABLE
(DATANOTA DATETIME NOT NULL);

DECLARE @ListaDatas AS ListarDatas;
INSERT INTO @ListaDatas (DATANOTA) VALUES ('20150101'), ('20171026'), ('20180328');

SELECT DATA, COUNT(*) AS NUMERO FROM [NOTAS FISCAIS]
WHERE DATA IN (SELECT DATANOTA FROM @ListaDatas)
GROUP BY DATA

CREATE PROCEDURE ListaNumeroNotas @LISTA_DATAS AS ListarDatas READONLY
AS
SELECT DATA, COUNT(*) AS NUMERO FROM [NOTAS FISCAIS]
WHERE DATA IN (SELECT DATANOTA FROM @LISTA_DATAS)
GROUP BY DATA

DECLARE @ListaDatas AS ListarDatas;
INSERT INTO @ListaDatas (DATANOTA) VALUES ('20150101'), ('20171026'), ('20180328');

EXEC ListaNumeroNotas @LISTA_DATAS = @ListaDatas;
