SELECT * FROM [TABELA DE CLIENTES];

SELECT * FROM [NOTAS FISCAIS] WHERE CPF = '1471156710';

CREATE FUNCTION ListaNotasClientes (@CPF AS VARCHAR(12)) RETURNS TABLE
AS
RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF

SELECT * FROM ListaNotasClientes('1471156710');

SELECT COUNT(*) FROM ListaNotasClientes('1471156710');

SELECT CPF, (SELECT COUNT(*) FROM ListaNotasClientes(CPF)) AS NUM_NOTA
FROM [TABELA DE CLIENTES]

SELECT A.CPF, A.NUM_NOTA, B.TOTAL_FATURAMENTO 
FROM
(SELECT CPF, (SELECT COUNT(*) FROM ListaNotasClientes(CPF)) AS NUM_NOTA
FROM [TABELA DE CLIENTES]) A
INNER JOIN
(SELECT CPF, SUM([dbo].[FaturamentoNota](NUMERO)) AS TOTAL_FATURAMENTO
FROM [NOTAS FISCAIS] GROUP BY CPF) B
ON A.CPF = B.CPF;



SELECT DISTINCT DATA, [dbo].[NUMERONOTAS](DATA) AS NUMERO 
FROM [NOTAS FISCAIS] WHERE DATA >= '20170101' AND DATA <= '20170110'

CREATE FUNCTION FuncTabelaNotas (@DATA_INICIAL AS DATE, @DATA_FINAL AS DATE) RETURNS TABLE
AS
RETURN SELECT DISTINCT DATA, [dbo].[NUMERONOTAS](DATA) AS NUMERO 
FROM [NOTAS FISCAIS] WHERE DATA >= @DATA_INICIAL AND DATA <= @DATA_FINAL

SELECT * FROM FuncTabelaNotas('20170101', '20170110');

SELECT DISTINCT DATA, [dbo].[NUMERONOTAS](DATA) AS NUMERO 
FROM [NOTAS FISCAIS] WHERE DATA >= '20170101' AND DATA <= '20170110';