CREATE FUNCTION EnderecoCompleto 
(@ENDERECO VARCHAR(100), @CIDADE VARCHAR(50), @ESTADO VARCHAR(50), @CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN
	DECLARE @ENDERECO_COMPLETO VARCHAR(250);
	SET @ENDERECO_COMPLETO = @ENDERECO + ' - ' + @CIDADE + ' - ' + @ESTADO + ' - ' + @CEP;
	RETURN @ENDERECO_COMPLETO;
END

SELECT CPF, [dbo].[EnderecoCompleto]([ENDERECO 1], CIDADE, ESTADO, CEP) AS END_COMPLETO FROM [TABELA DE CLIENTES]

ALTER FUNCTION EnderecoCompleto 
(@ENDERECO VARCHAR(100), @CIDADE VARCHAR(50), @ESTADO VARCHAR(50), @CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN
	DECLARE @ENDERECO_COMPLETO VARCHAR(250);
	SET @ENDERECO_COMPLETO = @ENDERECO + ', ' + @CIDADE + ', ' + @ESTADO + ', ' + @CEP;
	RETURN @ENDERECO_COMPLETO;
END

ALTER FUNCTION FuncTabelaNotas (@DATA_INICIAL AS DATE, @DATA_FINAL AS DATE) RETURNS TABLE
AS
RETURN SELECT DATA, COUNT(*) AS NUMERO FROM [NOTAS FISCAIS] 
WHERE DATA >= @DATA_INICIAL AND DATA <= @DATA_FINAL GROUP BY DATA;

SELECT * FROM FuncTabelaNotas('20170101', '20170110');

SELECT DISTINCT DATA, [dbo].[NUMERONOTAS](DATA) AS NUMERO 
FROM [NOTAS FISCAIS] WHERE DATA >= '20170101' AND DATA <= '20170110';