DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT, @LIMITE_BREAK INT;

SET @LIMITE_MINIMO = 1;
SET @LIMITE_MAXIMO = 10;
SET @LIMITE_BREAK = 12;

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	PRINT @LIMITE_MINIMO
	SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1;
	IF @LIMITE_MINIMO = @LIMITE_BREAK
	BEGIN
		PRINT 'Saindo por causa do Break';
		BREAK;
	END
END



DECLARE @DATA_INICIAL DATE, @DATA_FINAL DATE, @NUMERO_NOTAS INT;

SET @DATA_INICIAL = '2017-01-01';
SET @DATA_FINAL = '2017-01-10';

WHILE @DATA_INICIAL <= @DATA_FINAL
BEGIN
	SELECT @NUMERO_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATA_INICIAL;
	PRINT CONVERT(VARCHAR(10), @DATA_INICIAL) + ' --> ' + CONVERT(VARCHAR(10), @NUMERO_NOTAS);
	SELECT @DATA_INICIAL = DATEADD(DAY, 1, @DATA_INICIAL);
END



IF OBJECT_ID('TABELA DE NUMEROS', 'U') IS NOT NULL
	DROP TABLE [TABELA DE NUMEROS]

CREATE TABLE [TABELA DE NUMEROS] ([NUMERO] INT, [STATUS] VARCHAR(200))

DECLARE @LIMITE_MINIMO2 INT, @LIMITE_MAXIMO2 INT, @CONTADOR_NOTAS INT;

SET @LIMITE_MINIMO2 = 1;
SET @LIMITE_MAXIMO2 = 100000;

SET NOCOUNT ON -- NÃO ESCREVE VARIAS SAIDAS
WHILE @LIMITE_MINIMO2 <= @LIMITE_MAXIMO2
BEGIN
	SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE NUMERO = @LIMITE_MINIMO2;

	IF @CONTADOR_NOTAS > 0
		INSERT INTO [TABELA DE NUMEROS] (NUMERO, STATUS) VALUES (@LIMITE_MINIMO2, 'É nota fiscal');
	ELSE
		INSERT INTO [TABELA DE NUMEROS] (NUMERO, STATUS) VALUES (@LIMITE_MINIMO2, 'Não é nota fiscal');

	SET @LIMITE_MINIMO2 = @LIMITE_MINIMO2 + 1;
END

SELECT * FROM [TABELA DE NUMEROS]



IF OBJECT_ID('TABELA DE NUMEROS NOTAS', 'U') IS NOT NULL
	DROP TABLE [TABELA DE NUMEROS NOTAS]

CREATE TABLE [TABELA DE NUMEROS NOTAS] (DIA VARCHAR(20), NUMERO_NOTA INT);

DECLARE @DATA_INICIAL2 DATE, @DATA_FINAL2 DATE, @NUMERO_NOTAS2 INT, @DIA VARCHAR(20);

SET @DATA_INICIAL2 = '2017-01-01';
SET @DATA_FINAL2 = '2017-01-10';

WHILE @DATA_INICIAL2 <= @DATA_FINAL2
BEGIN
	SELECT @NUMERO_NOTAS2 = COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATA_INICIAL2;
	PRINT CONVERT(VARCHAR(10), @DATA_INICIAL2) + ' --> ' + CONVERT(VARCHAR(10), @NUMERO_NOTAS2);
	SET @DIA = DATENAME(WEEKDAY, @DATA_INICIAL2);
	INSERT INTO [TABELA DE NUMEROS NOTAS] (DIA, NUMERO_NOTA) VALUES (@DIA, @NUMERO_NOTAS2); 
	SELECT @DATA_INICIAL2 = DATEADD(DAY, 1, @DATA_INICIAL2);
END

SELECT * FROM [TABELA DE NUMEROS NOTAS];