DECLARE @NOME VARCHAR(200)
DECLARE CURSOR1 CURSOR FOR SELECT TOP 4 NOME FROM [TABELA DE CLIENTES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOME
	FETCH NEXT FROM CURSOR1 INTO @NOME
END


SELECT * FROM [TABELA DE CLIENTES]

DECLARE @LIMITE_CRETIDO FLOAT
DECLARE @LIMITE_CRETIDO_TOTAL FLOAT
SET @LIMITE_CRETIDO = 0
SET @LIMITE_CRETIDO_TOTAL = 0
DECLARE CURSOR2 CURSOR FOR SELECT [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]
OPEN CURSOR2
FETCH NEXT FROM CURSOR2 INTO @LIMITE_CRETIDO
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @LIMITE_CRETIDO_TOTAL = @LIMITE_CRETIDO_TOTAL + @LIMITE_CRETIDO
	FETCH NEXT FROM CURSOR2 INTO @LIMITE_CRETIDO
END
CLOSE CURSOR2
DEALLOCATE CURSOR2
PRINT @LIMITE_CRETIDO_TOTAL
