CREATE PROCEDURE CalculaIdade
AS
BEGIN
	UPDATE [TABELA DE CLIENTES] SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
END

INSERT INTO [TABELA DE CLIENTES] (CPF, NOME, [ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP, [DATA DE NASCIMENTO], SEXO, [LIMITE DE CREDITO], [VOLUME DE COMPRA], [PRIMEIRA COMPRA])
VALUES
('10606435611', 'JOAO MACHADO', 'RUA PROJETADA A', 'MADUREIRA', 'Rio de Janeiro', 'RJ', '200000', '20000306', 'M', 120000, 120000, 120000);

SELECT * FROM [TABELA DE CLIENTES] WHERE CPF = '10606435611'

EXEC CalculaIdade


SELECT * FROM [NOTAS FISCAIS]
SELECT * FROM [TABELA DE PRODUTOS]
SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT * FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
WHERE MONTH(NF.DATA) = 1
AND YEAR(NF.DATA) = 2017
AND P.EMBALAGEM = 'Lata'

UPDATE NF SET IMPOSTO = 0.13 
FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
WHERE MONTH(NF.DATA) = 1
AND YEAR(NF.DATA) = 2017
AND P.EMBALAGEM = 'Lata'

CREATE PROCEDURE AtualizaImposto @MES AS INT, @ANO AS INT, @ALIQUOTA AS FLOAT, @EMBALAGEM AS VARCHAR(20)
AS
BEGIN
	UPDATE NF SET IMPOSTO = @ALIQUOTA 
	FROM [NOTAS FISCAIS] NF
	INNER JOIN [ITENS NOTAS FISCAIS] INF 
	ON NF.NUMERO = INF.NUMERO
	INNER JOIN [TABELA DE PRODUTOS] P
	ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
	WHERE MONTH(NF.DATA) = @MES
	AND YEAR(NF.DATA) = @ANO
	AND P.EMBALAGEM = @EMBALAGEM
END

EXEC AtualizaImposto @MES = 1, @ANO = 2017, @ALIQUOTA = 0.15, @EMBALAGEM = 'Lata';