RESTORE VERIFYONLY FROM DISK = 'C:\temp\sql\SUCOS_VENDAS.BAK'

RESTORE HEADERONLY FROM DISK = 'C:\temp\sql\SUCOS_VENDAS.BAK'

ALTER DATABASE SUCOS_VENDAS SET RECOVERY FULL

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\temp\sql\SUCOS_VENDAS4.BAK' WITH INIT

SELECT * FROM [NOTAS FISCAIS] WHERE DATA = '20180405'
EXEC [dbo].[CriaNotaFiscal] '20180405'

USE MASTER
ALTER DATABASE SUCOS_VENDAS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE SUCOS_VENDAS
RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'C:\temp\sql\SUCOS_VENDAS4.BAK' WITH RECOVERY

-- 1 BACKUP FULL
-- 2 BACKUP LOG
-- 5 BACKUP DIFERENCIAL

USE SUCOS_VENDAS
SELECT * FROM [NOTAS FISCAIS] WHERE DATA = '20180405'

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\temp\sql\SUCOS_VENDAS5.BAK' WITH INIT

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\temp\sql\SUCOS_VENDAS5.BAK'

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\temp\sql\SUCOS_VENDAS5.BAK'

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'C:\temp\sql\SUCOS_VENDAS5.BAK'

RESTORE HEADERONLY FROM DISK = 'C:\temp\sql\SUCOS_VENDAS5.BAK'

USE master
ALTER DATABASE SUCOS_VENDAS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE SUCOS_VENDAS
RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'C:\temp\sql\SUCOS_VENDAS5.BAK' WITH FILE = 3, RECOVERY