CREATE TABLE ##TABELA02 (ID VARCHAR(10) NULL, NOME VARCHAR(200) NULL);

INSERT INTO ##TABELA02 (ID, NOME) VALUES ('1', 'JOÃO');

SELECT * FROM ##TABELA02;

INSERT INTO ##TABELA02 (ID, NOME) VALUES ('2', 'PAULO');