SELECT SUM(A.QUANTIDADE * A.[PREÇO]) AS FATURAMENTO,
SUM(A.QUANTIDADE * A.[PREÇO]) / 10 AS COMISSAO
FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO
WHERE B.CPF = '1471156710'
AND YEAR(B.DATA) = 2016;

SELECT * FROM [TABELA DE CLIENTES]

DECLARE @DENOMINADOR INT
SET @DENOMINADOR = 0

SELECT SUM(A.QUANTIDADE * A.[PREÇO]) AS FATURAMENTO,
SUM(A.QUANTIDADE * A.[PREÇO]) / @DENOMINADOR AS COMISSAO
FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO
WHERE B.CPF = '1471156710'
AND YEAR(B.DATA) = 2016;

CREATE PROCEDURE TrataErroZero 
@CPF AS VARCHAR(12), 
@ANO AS INT,
@DENOMINADOR AS INT,
@NUMERRO AS INT OUTPUT,
@NUMLINHA AS INT OUTPUT
AS
BEGIN
	SELECT SUM(A.QUANTIDADE * A.[PREÇO]) AS FATURAMENTO,
	SUM(A.QUANTIDADE * A.[PREÇO]) / @DENOMINADOR AS COMISSAO
	FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
	ON A.NUMERO = B.NUMERO
	WHERE B.CPF = @CPF
	AND YEAR(B.DATA) = @ANO;

	SELECT @NUMERRO = @@ERROR, @NUMLINHA = @@ROWCOUNT
END

DECLARE @DENOMINADOR INT;
DECLARE @CPF VARCHAR(12);
DECLARE @ANO INT;
DECLARE @NUMERRO INT;
DECLARE @NUMLINHA INT;

SET @CPF = '1471156710'
SET @ANO = 2016
SET @DENOMINADOR = 0

EXEC TrataErroZero @CPF, @ANO, @DENOMINADOR, @NUMERRO OUTPUT, @NUMLINHA OUTPUT

IF @NUMERRO <> 0
	PRINT 'Houve um erro: ' + CONVERT(VARCHAR(30), @NUMERRO) + ' - ' + CONVERT(VARCHAR(30), @NUMLINHA)

CREATE PROCEDURE InclusaoVendedor 
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50)
AS
BEGIN
INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
END

EXEC InclusaoVendedor '00238','Pericles Alves',0.11,'20160821',0,'Santo Amaro'

CREATE PROCEDURE InclusaoVendedor2
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50),
@NUMERRO AS INT OUTPUT,
@NUMLINHA AS INT OUTPUT
AS
BEGIN
INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)

SELECT @NUMERRO = @@ERROR, @NUMLINHA = @@ROWCOUNT
END

DECLARE @NUMERRO INT, @NUMLINHA INT

EXEC InclusaoVendedor2 '00238','Pericles Alves',0.11,'20160821',0,'Santo Amaro', @NUMERRO OUTPUT, @NUMLINHA OUTPUT

IF @NUMERRO <> 0
	PRINT 'Houve um erro: ' + CONVERT(VARCHAR(30), @NUMERRO) + ' - ' + CONVERT(VARCHAR(30), @NUMLINHA)