CREATE PROCEDURE TrataErroZeroTry
@CPF AS VARCHAR(12), 
@ANO AS INT,
@DENOMINADOR AS INT,
@MESSAGEM VARCHAR(50) OUTPUT
AS
BEGIN
	BEGIN TRY
		SELECT SUM(A.QUANTIDADE * A.[PREÇO]) AS FATURAMENTO,
		SUM(A.QUANTIDADE * A.[PREÇO]) / @DENOMINADOR AS COMISSAO
		FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
		ON A.NUMERO = B.NUMERO
		WHERE B.CPF = @CPF
		AND YEAR(B.DATA) = @ANO;
	END TRY
	BEGIN CATCH
		SET @MESSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR(10), @@ERROR)
	END CATCH
END

SELECT * FROM [TABELA DE CLIENTES]

DECLARE @DENOMINADOR INT
DECLARE @CPF VARCHAR(12)
DECLARE @ANO INT
DECLARE @MESSAGEM VARCHAR(30)

SET @CPF = '1471156710'
SET @ANO = 2016
SET @DENOMINADOR = 0
SET @MESSAGEM = ''

EXEC TrataErroZeroTry @CPF, @ANO, @DENOMINADOR, @MESSAGEM OUTPUT

IF @MESSAGEM <> ''
	PRINT @MESSAGEM



CREATE PROCEDURE InclusaoVendedor3
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50),
@MESSAGEM VARCHAR(30) OUTPUT
AS
BEGIN
	BEGIN TRY
		INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
		VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
	END TRY
	BEGIN CATCH
		SET @MESSAGEM = 'Houve um erro numero: ' + CONVERT(VARCHAR(30), @@ERROR)
	END CATCH
END

DECLARE @MESSAGEM VARCHAR(30)
SET @MESSAGEM = '';

EXEC InclusaoVendedor3 '00238','Pericles Alves',0.11,'20160821',0,'Santo Amaro', @MESSAGEM OUTPUT

IF @MESSAGEM <> ''
	PRINT @MESSAGEM