SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [NOTAS FISCAIS]

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT P.SABOR FROM [TABELA DE PRODUTOS] P

SELECT NF.[DATA] FROM [NOTAS FISCAIS] NF

SELECT (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO FROM [ITENS NOTAS FISCAIS] INF

SELECT P.SABOR, NF.[DATA], (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO 
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO

SELECT P.SABOR, YEAR(NF.[DATA]), SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO 
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
GROUP BY P.SABOR, YEAR(NF.[DATA])

SELECT P.SABOR, YEAR(NF.[DATA]), SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO 
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY P.SABOR, YEAR(NF.[DATA])

SELECT YEAR(NF.[DATA]), SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO 
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY YEAR(NF.[DATA])

SELECT AUX1.SABOR, AUX1.ANO, 
CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO,
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), (AUX1.FATURAMENTO/AUX2.TOTAL) * 100)) + '%' AS PERCENTUAL
FROM
(SELECT P.SABOR, YEAR(NF.[DATA]) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO 
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY P.SABOR, YEAR(NF.[DATA])) AUX1
INNER JOIN (SELECT YEAR(NF.[DATA]) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS TOTAL 
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY YEAR(NF.[DATA])) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC

SELECT AUX1.TAMANHO, AUX1.ANO, 
CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO,
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), (AUX1.FATURAMENTO/AUX2.TOTAL) * 100)) + '%' AS PERCENTUAL
FROM
(SELECT P.TAMANHO, YEAR(NF.[DATA]) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO 
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY P.TAMANHO, YEAR(NF.[DATA])) AUX1
INNER JOIN (SELECT YEAR(NF.[DATA]) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS TOTAL 
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [TABELA DE PRODUTOS] P
ON P.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.[DATA]) = 2016
GROUP BY YEAR(NF.[DATA])) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC