SELECT * FROM master.sys.sql_logins;

SELECT name, LOGINPROPERTY(name, 'PasswordLastSetTime') FROM master.sys.sql_logins

CREATE LOGIN pedro WITH PASSWORD = 'pedro'

SELECT SERVERPROPERTY('MARCOSERVIO\SQLEXPRESS') AS SERVER_NAME, NAME AS LOGIN_NAME FROM master.sys.sql_logins
WHERE PWDCOMPARE(NAME, PASSWORD_HASH) = 1

SELECT SERVERPROPERTY('MARCOSERVIO\SQLEXPRESS') AS SERVER_NAME, NAME AS LOGIN_NAME FROM master.sys.sql_logins
WHERE PWDCOMPARE(NAME, PASSWORD_HASH) <> 1