# Generated by Django 5.0.1 on 2024-01-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
