- hosts: terraform-ansible
  tasks:
    - name: criando o arquivo
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>Esse bilhete é verdade</h1>
    - name: criando o servidor
      shell: "nohup busybox httpd -f -p 8080 &"
    - name: Instalando o python3 virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: true #apt update e apt upgrade
      become: true #usuario root
    - name: Instalando dependencias com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Iniciando o projeto
      shell: ". /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/"
      ignore_errors: true
    - name: Alterando o hosts do settings
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: "ALLOWED_HOSTS"
        line: "ALLOWED_HOSTS = ['*']"
        backrefs: yes
    # - name: Subindo servidor django
    #   shell: ". tcc/venv/bin/activate; python tcc/manage.py runserver 0.0.0.0:8000 &"
